#page title
page_title                                : NeverSkip Fitness                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1560521531                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : at                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://testflight.apple.com/join/8n2wAXrn                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=io.hawkford.fredericapp                                          # Enter Google Play Store URL.
presskit_download_link                    : /assets/neverskip_presskit.zip                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : NeverSkip Fitness                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : € 6.99 (with a 30 day free trial)                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Ever set a fitness goal and quit halfway through? NeverSkip keeps you motivated all the way through and helps you build healthy behaviors.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Felix Holz                                
your_link                                 :                      
your_city                                 : Graz, AT                                
email_address                             : 
facebook_username                         :                                           
instagram_username                        : nextormer
twitter_username                          : 
github_username                           : nextormer
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Calendar
    description                           : A beautiful and simple calendar which shows you the upcoming exercises from your workout plan.
    fontawesome_icon_name                 : calendar-week
    
  - title                                 : Performance tracking
    description                           : Document your fitness journey. See how well you did last workout and how far you have come.
    fontawesome_icon_name                 : chart-line

  - title                                 : Workout planner
    description                           : Plan your own workouts with your own schedule, or use a workout provided by us.
    fontawesome_icon_name                 : calendar-alt

  - title                                 : Charts and analysis
    description                           : Various charts let you keep an eye on your progress and keeps you motivated.
    fontawesome_icon_name                 : chart-bar

  - title                                 : Goals and achievements
    description                           : Set goals for specific exercises, or anything else you want. Your completed goals are displayed in a list of all your achievements.
    fontawesome_icon_name                 : bullseye
  
  - title                                 : Simple design
    description                           : NeverSkip is designed to make the user-experience as simple as possible to not get in the way of your training.
    fontawesome_icon_name                 : object-group

#  - title                                 : Smart App Banner
#    description                           : Display a smart app banner on iOS devices.
#    fontawesome_icon_name                 : arrow-alt-circle-down

#  - title                                 : Social Links
#    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : link

#  - title                                 : FontAwesome Support
#    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : info-circle

#  - title                                 : # New Feature Title
#    description                           : # New Feature Description
#    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/background.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#4ecbf5" # "#363b3d"
cover_overlay_transparency                : 1.0

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
